[package]
name = "lsaver"
version = "0.1.0"
authors = ["David Haig <david@ninjametal.com>"]
edition = "2018"

[dependencies]
piston_window = "0.107"
#crossbeam = "0.7.3"
piston = "0.49"
piston2d-graphics = "0.36"
pistoncore-glutin_window = "0.63"
piston2d-opengl_graphics = "0.72"
rand = "0.7"